
CREATE TABLE `research`.`T_ACCOUNT` (
  `ACCN_ID` varchar(35) NOT NULL,
  `ACCN_NUMBER` varchar(100) NOT NULL,
  `ACCN_NAME` varchar(100) NOT NULL,
  `ACCN_BRANCH` varchar(100) NOT NULL,
  `ACCN_STATUS` varchar(1) NOT NULL,
  PRIMARY KEY (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `research`.`T_EMPLOYEE` (
  `EMP_ID` varchar(35) NOT NULL,
  `EMP_NAME` varchar(100) NOT NULL,
  `EMP_DESIGN` varchar(100) NOT NULL,
  `EMP_DEPT` varchar(100) NOT NULL,
  `EMP_ADDRESS` varchar(100) DEFAULT NULL,
  `EMP_STATUS` varchar(1) NOT NULL,
  `EMP_ACCN_ID` varchar(35) NOT NULL,
  PRIMARY KEY (`EMP_ID`),
  KEY `FKY__T_EMPLOYEE__EMP_ACCN_ID_IDX` (`EMP_ACCN_ID`),
  CONSTRAINT `FKY__T_EMPLOYEE__EMP_ACCN_ID` FOREIGN KEY (`EMP_ACCN_ID`) REFERENCES `T_ACCOUNT` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
